### ISSUE TITLE
Breaking blocks dropping tps to 3 

### ISSUE THREAD

**Issue by FallingCactus** [TheBusyBiscuit/ColoredEnderChests#9] opened 2020-01-10 22:22 UTC
**Description** (Required)
dev builds of Coloured Ender Chests killing TPS in 1.15.1 when players mine, worse with mcMMO superbreaker.

**Steps to reproduce the Issue** (Required)
1 player using mcmmo super breaker drops tps
slight fluctuations when using a maxed out vanilla pick (1 player) 

**Expected behavior** (Required)
Expected no tps drop issues breaking blocks.

**Timings Report**
https://timings.aikar.co/?id=3fb5f4e2a0714d948eeaa38fe7fbf452#timings

**Environment** (Required)
Server Version: PaperMC build 42 1.15.1

Paper v1_15_R1
CS-CoreLib vDEV - 80 (git e3242c60)
Slimefun vRC - 4 (git ec409886)
Installed Addons (3)
ChestTerminal vDEV - 20 (git a698c614)
ExoticGarden vDEV - 24 (git 4a0e0c0e)
SlimyTreeTaps vDEV - 4 (git e24e74d2)

**Comment by TheBusyBiscuit** [comment] 2020-01-10 22:29
Duplicate of #8

**Closed by TheBusyBiscuit** 2020-01-10 22:29 UTC
